### ISSUE TITLE
a few basic question to get started

### ISSUE THREAD

**Issue by or-dvir** [UdiOshi85/GenericSettings#1]
Hi
i have lately came across multiple problems trying to implement a settings (AKA preference) activity/fragment in my app and i am extremely frustrated - and now i came across your library.
the library looks good and from the brief look ive had at the code it seems easy to implement - however i have a few questions:

1. is this a REAL PreferenceActivity (or fragment)??? i mean is it directly connected to shared preferences and does it immediately edits the values of those sharedPreferences? or is this simply and activity that only LOOKS LIKE a preferenceActivity?

1. if it is indeed a real preferenceActivity, then i do not see anything related to the preferences' keys. how do i retrieve the values of my preferences? do i have to manage the values of me preferences manually?

1. in class` BasicTypesPresenter`, i am confused about the constructor having a coordinateLayout parameter - do i have to pass a layout to my own constructor? does it have to be a coordinateLayout? or is did you just do it so you can show the snack bar?

thanks

**Comment by UdiOshi85** [comment]
Hi Or,

1 & 2. Currently its just look like PrefereneceActivity, in the next couple weeks the library will be integrated with shared preferences / some other database to store all values.
I'm working on this alone and it takes sometime between version to version :) so currently you can work with this library for UI and implement your own shared preferences in your presenter (By  overriding BaseSettingsPresenter methods)

3. You probably compiled old code. Presenters doesn't need Coordinatorlayout anymore.
I've just check 1.4.1 version and it's ok.

As it's feature request (which is already during development) i'm closing it.
If you need anything else please contact via email: udioshi@gmail.com

**Comment by UdiOshi85** [comment]
BTW,

I'm using Coordinatorlayout in the example app in order to show snackbar on clicks.
You should extend BasticSettingsPresenter and do whatever you want in it

**Comment by or-dvir** [comment]
thanks for you fast reply!
i downloaded this project yesterday (feb 19th 2018) directly to my computer so its not "old code"

**Comment by UdiOshi85** [comment]
So as you can see you don't need to pass CoordinatorLayout to your presener
as you need to extend BaseSettingsPresenter
